### ISSUE TITLE
Can we have setup for linux circleci?

### ISSUE THREAD

**Issue by arpit2438735** [SBats/tns-circleci-example#2]
Mac OS is paid in circleci , so for open source project I want to setup Android test but I am unable to setup.Getting lot of issue in running test on android in circleci. Can you showcase some example for android platform in linux docker image?

**Comment by SBats** [comment]
Hi! Unfortunately, I don't currently have examples of the setup for a Linux machine. Do you have a bit more context on where/when/why it fails?
Other than that, don't hesitate to [ask the CircleCI team](https://discuss.circleci.com/) for help or hints. They are usually really friendly and helpful :)

EDIT: Also worth remembering if your project is open-source, you can contact CircleCI to have a free MacOS plan

**Comment by arpit2438735** [comment]
Thanks @SBats I created a ticket in CircleCi.

It fails when I try to run test cases for android.Here's my configuration to run the test
```
test-unit-android:
      <<: *default_config
      steps:
        - attach_workspace:
            at: ~/

        - run:
            name: Setup emulator
            command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"

        - run:
            name: Launch emulator
            command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
            background: true

        - run:
            name: Wait emulator
            command: |
              circle-android wait-for-boot
              sleep 30
              adb shell input keyevent 82

        - run:
            name: "Build and Run unit tests For Android"
            command: |
              npx tns usage-reporting disable
              npx tns error-reporting disable
              
              npx tns test android --emulator --justlaunch
```      
Screenshot of my error message:-
<img width="1175" alt="screen shot 2018-07-13 at 7 39 14 pm" src="https://user-images.githubusercontent.com/398390/42695953-78362668-86d4-11e8-9dbd-b111ee0b9be3.png">
.
